### ISSUE TITLE
fix pls #1

### ISSUE THREAD

**Issue by Unkorunk** [justTakhir/ACID-Double-Linked-List#7]
- [x] https://github.com/justTakhir/ACID-Double-Linked-List/blob/23d704f01379c8bc429890bcd6f7bd1b0dfd9438/Double%20Linked%20List/TrueNode.h#L10

- [x] https://github.com/justTakhir/ACID-Double-Linked-List/blob/23d704f01379c8bc429890bcd6f7bd1b0dfd9438/Double%20Linked%20List/SentinelingNode.h#L10

- [x] https://github.com/justTakhir/ACID-Double-Linked-List/blob/23d704f01379c8bc429890bcd6f7bd1b0dfd9438/Double%20Linked%20List/ConstIterator.h#L3

- [x] https://github.com/justTakhir/ACID-Double-Linked-List/blob/23d704f01379c8bc429890bcd6f7bd1b0dfd9438/Double%20Linked%20List/ConstIterator.h#L78

- [x] https://github.com/justTakhir/ACID-Double-Linked-List/blob/23d704f01379c8bc429890bcd6f7bd1b0dfd9438/Double%20Linked%20List/Node.h#L25

**Comment by justTakhir** [comment]
tnx
